        Exception 1:
       at UnitTester.Program.DivByZero() in <snip>\Dev\UnitTester\Program.cs:line 49
       at UnitTester.Program.ThrowException1() in <snip>\Dev\UnitTester\Program.cs:line 36
       at UnitTester.Program.TestExceptions() in <snip>\Dev\UnitTester\Program.cs:line 19
    
    Exception 2:
       at UnitTester.Program.ThrowException2() in <snip>\Dev\UnitTester\Program.cs:line 43
       at UnitTester.Program.TestExceptions() in <snip>\Dev\UnitTester\Program.cs:line 25
